/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-28 at 05:58:31 UTC 
 * Modify at your own risk.
 */

package com.appspot.seekret_dev.spotAPI.model;

/**
 * Model definition for Cluster.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the spotAPI. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Cluster extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String datastoreClusterKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer dismissCounter;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double latitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double longitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numberOfPOIs;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double overallTouristicnessInPointsFrom1To10;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer overallTouristicnessVotes;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer overallViews;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<PointOfInterest> pointOfInterestList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> urlOfMostViewedPicture;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDatastoreClusterKey() {
    return datastoreClusterKey;
  }

  /**
   * @param datastoreClusterKey datastoreClusterKey or {@code null} for none
   */
  public Cluster setDatastoreClusterKey(java.lang.String datastoreClusterKey) {
    this.datastoreClusterKey = datastoreClusterKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public Cluster setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDismissCounter() {
    return dismissCounter;
  }

  /**
   * @param dismissCounter dismissCounter or {@code null} for none
   */
  public Cluster setDismissCounter(java.lang.Integer dismissCounter) {
    this.dismissCounter = dismissCounter;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLatitude() {
    return latitude;
  }

  /**
   * @param latitude latitude or {@code null} for none
   */
  public Cluster setLatitude(java.lang.Double latitude) {
    this.latitude = latitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLongitude() {
    return longitude;
  }

  /**
   * @param longitude longitude or {@code null} for none
   */
  public Cluster setLongitude(java.lang.Double longitude) {
    this.longitude = longitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Cluster setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumberOfPOIs() {
    return numberOfPOIs;
  }

  /**
   * @param numberOfPOIs numberOfPOIs or {@code null} for none
   */
  public Cluster setNumberOfPOIs(java.lang.Integer numberOfPOIs) {
    this.numberOfPOIs = numberOfPOIs;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getOverallTouristicnessInPointsFrom1To10() {
    return overallTouristicnessInPointsFrom1To10;
  }

  /**
   * @param overallTouristicnessInPointsFrom1To10 overallTouristicnessInPointsFrom1To10 or {@code null} for none
   */
  public Cluster setOverallTouristicnessInPointsFrom1To10(java.lang.Double overallTouristicnessInPointsFrom1To10) {
    this.overallTouristicnessInPointsFrom1To10 = overallTouristicnessInPointsFrom1To10;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getOverallTouristicnessVotes() {
    return overallTouristicnessVotes;
  }

  /**
   * @param overallTouristicnessVotes overallTouristicnessVotes or {@code null} for none
   */
  public Cluster setOverallTouristicnessVotes(java.lang.Integer overallTouristicnessVotes) {
    this.overallTouristicnessVotes = overallTouristicnessVotes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getOverallViews() {
    return overallViews;
  }

  /**
   * @param overallViews overallViews or {@code null} for none
   */
  public Cluster setOverallViews(java.lang.Integer overallViews) {
    this.overallViews = overallViews;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<PointOfInterest> getPointOfInterestList() {
    return pointOfInterestList;
  }

  /**
   * @param pointOfInterestList pointOfInterestList or {@code null} for none
   */
  public Cluster setPointOfInterestList(java.util.List<PointOfInterest> pointOfInterestList) {
    this.pointOfInterestList = pointOfInterestList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getUrlOfMostViewedPicture() {
    return urlOfMostViewedPicture;
  }

  /**
   * @param urlOfMostViewedPicture urlOfMostViewedPicture or {@code null} for none
   */
  public Cluster setUrlOfMostViewedPicture(java.util.List<java.lang.String> urlOfMostViewedPicture) {
    this.urlOfMostViewedPicture = urlOfMostViewedPicture;
    return this;
  }

  @Override
  public Cluster set(String fieldName, Object value) {
    return (Cluster) super.set(fieldName, value);
  }

  @Override
  public Cluster clone() {
    return (Cluster) super.clone();
  }

}
