/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-09-24 at 15:05:38 UTC 
 * Modify at your own risk.
 */

package com.appspot.seekret_dev.spotAPI.model;

/**
 * Model definition for PointOfInterest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the spotAPI. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PointOfInterest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer countOfViews;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer height;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer licenseId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private LatLng location;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pictureUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> tags;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer width;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getCountOfViews() {
    return countOfViews;
  }

  /**
   * @param countOfViews countOfViews or {@code null} for none
   */
  public PointOfInterest setCountOfViews(java.lang.Integer countOfViews) {
    this.countOfViews = countOfViews;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getHeight() {
    return height;
  }

  /**
   * @param height height or {@code null} for none
   */
  public PointOfInterest setHeight(java.lang.Integer height) {
    this.height = height;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLicenseId() {
    return licenseId;
  }

  /**
   * @param licenseId licenseId or {@code null} for none
   */
  public PointOfInterest setLicenseId(java.lang.Integer licenseId) {
    this.licenseId = licenseId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public LatLng getLocation() {
    return location;
  }

  /**
   * @param location location or {@code null} for none
   */
  public PointOfInterest setLocation(LatLng location) {
    this.location = location;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPictureUrl() {
    return pictureUrl;
  }

  /**
   * @param pictureUrl pictureUrl or {@code null} for none
   */
  public PointOfInterest setPictureUrl(java.lang.String pictureUrl) {
    this.pictureUrl = pictureUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getTags() {
    return tags;
  }

  /**
   * @param tags tags or {@code null} for none
   */
  public PointOfInterest setTags(java.util.List<java.lang.String> tags) {
    this.tags = tags;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getWidth() {
    return width;
  }

  /**
   * @param width width or {@code null} for none
   */
  public PointOfInterest setWidth(java.lang.Integer width) {
    this.width = width;
    return this;
  }

  @Override
  public PointOfInterest set(String fieldName, Object value) {
    return (PointOfInterest) super.set(fieldName, value);
  }

  @Override
  public PointOfInterest clone() {
    return (PointOfInterest) super.clone();
  }

}
