/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-26 at 09:31:56 UTC 
 * Modify at your own risk.
 */

package com.appspot.seekret_dev.spotAPI.model;

/**
 * Model definition for Response.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the spotAPI. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Response extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Object entity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private JsonMap metadata;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer status;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Object getEntity() {
    return entity;
  }

  /**
   * @param entity entity or {@code null} for none
   */
  public Response setEntity(java.lang.Object entity) {
    this.entity = entity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public JsonMap getMetadata() {
    return metadata;
  }

  /**
   * @param metadata metadata or {@code null} for none
   */
  public Response setMetadata(JsonMap metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public Response setStatus(java.lang.Integer status) {
    this.status = status;
    return this;
  }

  @Override
  public Response set(String fieldName, Object value) {
    return (Response) super.set(fieldName, value);
  }

  @Override
  public Response clone() {
    return (Response) super.clone();
  }

}
