/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLClusterAPIJsonMap.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   clusterAPI/v1
// Description:
//   This API serves everything needed to update a cluster.
// Classes:
//   GTLClusterAPIJsonMap (0 custom class methods, 0 custom properties)

#import "GTLClusterAPIJsonMap.h"

// ----------------------------------------------------------------------------
//
//   GTLClusterAPIJsonMap
//

@implementation GTLClusterAPIJsonMap
@end
