/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLClusterAPIAddress.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   clusterAPI/v1
// Description:
//   This API serves everything needed to update a cluster.
// Classes:
//   GTLClusterAPIAddress (0 custom class methods, 1 custom properties)

#import "GTLClusterAPIAddress.h"

// ----------------------------------------------------------------------------
//
//   GTLClusterAPIAddress
//

@implementation GTLClusterAPIAddress
@dynamic address;
@end
