/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLClusterAPIJsonMap.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   clusterAPI/v1
// Description:
//   This API serves everything needed to update a cluster.
// Classes:
//   GTLClusterAPIJsonMap (0 custom class methods, 0 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLClusterAPIJsonMap
//

@interface GTLClusterAPIJsonMap : GTLObject
@end
