/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLClusterAPIResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   clusterAPI/v1
// Description:
//   This API serves everything needed to update a cluster.
// Classes:
//   GTLClusterAPIResponse (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLClusterAPIJsonMap;

// ----------------------------------------------------------------------------
//
//   GTLClusterAPIResponse
//

@interface GTLClusterAPIResponse : GTLObject
@property (retain) id entity;
@property (retain) GTLClusterAPIJsonMap *metadata;
@property (retain) NSNumber *status;  // intValue
@end
