/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLClusterAPIResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   clusterAPI/v1
// Description:
//   This API serves everything needed to update a cluster.
// Classes:
//   GTLClusterAPIResponse (0 custom class methods, 3 custom properties)

#import "GTLClusterAPIResponse.h"

#import "GTLClusterAPIJsonMap.h"

// ----------------------------------------------------------------------------
//
//   GTLClusterAPIResponse
//

@implementation GTLClusterAPIResponse
@dynamic entity, metadata, status;
@end
