/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQuerySpotAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLQuerySpotAPI (4 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQuerySpotAPI : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (assign) BOOL onlyExcludedPictures;
@property (copy) NSString *spotId;
@property (copy) NSString *spotName;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQuerySpotAPI object.

// Method: spotAPI.getNearestSpotByAddress
//  Authorization scope(s):
//   kGTLAuthScopeSpotAPIUserinfoEmail
// Fetches a GTLSpotAPISpot.
+ (id)queryForGetNearestSpotByAddressWithSpotName:(NSString *)spotName;

// Method: spotAPI.getSpotById
//  Authorization scope(s):
//   kGTLAuthScopeSpotAPIUserinfoEmail
// Fetches a GTLSpotAPISpot.
+ (id)queryForGetSpotByIdWithSpotId:(NSString *)spotId;

// Method: spotAPI.getSpotByNamePutToCrawlQueue
//  Authorization scope(s):
//   kGTLAuthScopeSpotAPIUserinfoEmail
// Fetches a GTLSpotAPIResponse.
+ (id)queryForGetSpotByNamePutToCrawlQueueWithSpotName:(NSString *)spotName
                                  onlyExcludedPictures:(BOOL)onlyExcludedPictures;

// Method: spotAPI.getTopSpots
//  Authorization scope(s):
//   kGTLAuthScopeSpotAPIUserinfoEmail
// Fetches a GTLSpotAPISpotResultList.
+ (id)queryForGetTopSpots;

@end
