/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryClusterAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   clusterAPI/v1
// Description:
//   This API serves everything needed to update a cluster.
// Classes:
//   GTLQueryClusterAPI (3 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQueryClusterAPI : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *datastoreKeyOfCluster;
@property (assign) double latitude;
@property (assign) double longitude;
@property (copy) NSString *spotName;
@property (assign) NSInteger touristicnessRatingFrom1To10;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryClusterAPI object.

// Method: clusterAPI.evaluateCluster
//  Authorization scope(s):
//   kGTLAuthScopeClusterAPIUserinfoEmail
// Fetches a GTLClusterAPIResponse.
+ (id)queryForEvaluateClusterWithDatastoreKeyOfCluster:(NSString *)datastoreKeyOfCluster
                          touristicnessRatingFrom1To10:(NSInteger)touristicnessRatingFrom1To10
                                              spotName:(NSString *)spotName;

// Method: clusterAPI.getAddressFromLatLng
//  Authorization scope(s):
//   kGTLAuthScopeClusterAPIUserinfoEmail
// Fetches a GTLClusterAPIAddress.
+ (id)queryForGetAddressFromLatLngWithLatitude:(double)latitude
                                     longitude:(double)longitude;

// Method: clusterAPI.incrementDismissCount
//  Authorization scope(s):
//   kGTLAuthScopeClusterAPIUserinfoEmail
// Fetches a GTLClusterAPIResponse.
+ (id)queryForIncrementDismissCountWithDatastoreKeyOfCluster:(NSString *)datastoreKeyOfCluster;

@end
