/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.

#import "GTLSpotAPIConstants.h"

#import "GTLSpotAPICluster.h"
#import "GTLSpotAPIJsonMap.h"
#import "GTLSpotAPIKey.h"
#import "GTLSpotAPILatLng.h"
#import "GTLSpotAPIPointOfInterest.h"
#import "GTLSpotAPIResponse.h"
#import "GTLSpotAPISpot.h"
#import "GTLSpotAPISpotResultList.h"

#import "GTLQuerySpotAPI.h"
#import "GTLServiceSpotAPI.h"
