/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPIResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLSpotAPIResponse (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLSpotAPIJsonMap;

// ----------------------------------------------------------------------------
//
//   GTLSpotAPIResponse
//

@interface GTLSpotAPIResponse : GTLObject
@property (retain) id entity;
@property (retain) GTLSpotAPIJsonMap *metadata;
@property (retain) NSNumber *status;  // intValue
@end
