/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPISpotResultList.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLSpotAPISpotResultList (0 custom class methods, 1 custom properties)

#import "GTLSpotAPISpotResultList.h"

// ----------------------------------------------------------------------------
//
//   GTLSpotAPISpotResultList
//

@implementation GTLSpotAPISpotResultList
@dynamic topSpots;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[NSString class]
                                forKey:@"topSpots"];
  return map;
}

@end
