/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPIPointOfInterest.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLSpotAPIPointOfInterest (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLSpotAPILatLng;

// ----------------------------------------------------------------------------
//
//   GTLSpotAPIPointOfInterest
//

@interface GTLSpotAPIPointOfInterest : GTLObject
@property (retain) NSNumber *countOfViews;  // intValue
@property (retain) GTLSpotAPILatLng *location;
@property (copy) NSString *pictureUrl;
@property (retain) NSArray *tags;  // of NSString
@end
