/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPIConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.

#import "GTLSpotAPIConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeSpotAPIUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
