/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPIKey.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLSpotAPIKey (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLSpotAPIKey;

// ----------------------------------------------------------------------------
//
//   GTLSpotAPIKey
//

@interface GTLSpotAPIKey : GTLObject
@property (copy) NSString *appId;
@property (retain) NSNumber *complete;  // boolValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (copy) NSString *kind;
@property (copy) NSString *name;

// Remapped to 'namespaceProperty' to avoid language reserved word 'namespace'.
@property (copy) NSString *namespaceProperty;

@property (retain) GTLSpotAPIKey *parent;
@end
