/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLClusterAPIConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   clusterAPI/v1
// Description:
//   This API serves everything needed to update a cluster.

#import "GTLClusterAPIConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeClusterAPIUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
