/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLClusterAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   clusterAPI/v1
// Description:
//   This API serves everything needed to update a cluster.

#import "GTLClusterAPIConstants.h"

#import "GTLClusterAPIAddress.h"
#import "GTLClusterAPIJsonMap.h"
#import "GTLClusterAPIResponse.h"

#import "GTLQueryClusterAPI.h"
#import "GTLServiceClusterAPI.h"
