/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryRatingAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   ratingAPI/v1
// Description:
//   This API serves everything needed for Ratings
// Classes:
//   GTLQueryRatingAPI (6 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQueryRatingAPI : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *clusterPrimaryKey;
@property (copy) NSString *userPrimaryKey;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryRatingAPI object.

// Method: ratingAPI.addNewRating
//  Authorization scope(s):
//   kGTLAuthScopeRatingAPIUserinfoEmail
// Fetches a GTLRatingAPIResponse.
+ (id)queryForAddNewRatingWithClusterPrimaryKey:(NSString *)clusterPrimaryKey;

// Method: ratingAPI.getAllDismissKeysOfSpecifiedUser
//  Authorization scope(s):
//   kGTLAuthScopeRatingAPIUserinfoEmail
// Fetches a GTLRatingAPIKeyResult.
+ (id)queryForGetAllDismissKeysOfSpecifiedUserWithUserPrimaryKey:(NSString *)userPrimaryKey;

// Method: ratingAPI.getAllRatingKeysOfSpecifiedUser
//  Authorization scope(s):
//   kGTLAuthScopeRatingAPIUserinfoEmail
// Fetches a GTLRatingAPIKeyResult.
+ (id)queryForGetAllRatingKeysOfSpecifiedUserWithUserPrimaryKey:(NSString *)userPrimaryKey;

// Method: ratingAPI.hasAlreadyDismissed
//  Authorization scope(s):
//   kGTLAuthScopeRatingAPIUserinfoEmail
// Fetches a GTLRatingAPIResponse.
+ (id)queryForHasAlreadyDismissedWithClusterPrimaryKey:(NSString *)clusterPrimaryKey;

// Method: ratingAPI.hasAlreadyDismissedOrVoted
//  Authorization scope(s):
//   kGTLAuthScopeRatingAPIUserinfoEmail
// Fetches a GTLRatingAPIResponse.
+ (id)queryForHasAlreadyDismissedOrVotedWithClusterPrimaryKey:(NSString *)clusterPrimaryKey;

// Method: ratingAPI.hasUserAlreadyVoted
//  Authorization scope(s):
//   kGTLAuthScopeRatingAPIUserinfoEmail
// Fetches a GTLRatingAPIResponse.
+ (id)queryForHasUserAlreadyVotedWithClusterPrimaryKey:(NSString *)clusterPrimaryKey;

@end
