/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryRatingAPI.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   ratingAPI/v1
// Description:
//   This API serves everything needed for Ratings
// Classes:
//   GTLQueryRatingAPI (6 custom class methods, 3 custom properties)

#import "GTLQueryRatingAPI.h"

#import "GTLRatingAPIKeyResult.h"
#import "GTLRatingAPIResponse.h"

@implementation GTLQueryRatingAPI

@dynamic clusterPrimaryKey, fields, userPrimaryKey;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryRatingAPI object.

+ (id)queryForAddNewRatingWithClusterPrimaryKey:(NSString *)clusterPrimaryKey {
  NSString *methodName = @"ratingAPI.addNewRating";
  GTLQueryRatingAPI *query = [self queryWithMethodName:methodName];
  query.clusterPrimaryKey = clusterPrimaryKey;
  query.expectedObjectClass = [GTLRatingAPIResponse class];
  return query;
}

+ (id)queryForGetAllDismissKeysOfSpecifiedUserWithUserPrimaryKey:(NSString *)userPrimaryKey {
  NSString *methodName = @"ratingAPI.getAllDismissKeysOfSpecifiedUser";
  GTLQueryRatingAPI *query = [self queryWithMethodName:methodName];
  query.userPrimaryKey = userPrimaryKey;
  query.expectedObjectClass = [GTLRatingAPIKeyResult class];
  return query;
}

+ (id)queryForGetAllRatingKeysOfSpecifiedUserWithUserPrimaryKey:(NSString *)userPrimaryKey {
  NSString *methodName = @"ratingAPI.getAllRatingKeysOfSpecifiedUser";
  GTLQueryRatingAPI *query = [self queryWithMethodName:methodName];
  query.userPrimaryKey = userPrimaryKey;
  query.expectedObjectClass = [GTLRatingAPIKeyResult class];
  return query;
}

+ (id)queryForHasAlreadyDismissedWithClusterPrimaryKey:(NSString *)clusterPrimaryKey {
  NSString *methodName = @"ratingAPI.hasAlreadyDismissed";
  GTLQueryRatingAPI *query = [self queryWithMethodName:methodName];
  query.clusterPrimaryKey = clusterPrimaryKey;
  query.expectedObjectClass = [GTLRatingAPIResponse class];
  return query;
}

+ (id)queryForHasAlreadyDismissedOrVotedWithClusterPrimaryKey:(NSString *)clusterPrimaryKey {
  NSString *methodName = @"ratingAPI.hasAlreadyDismissedOrVoted";
  GTLQueryRatingAPI *query = [self queryWithMethodName:methodName];
  query.clusterPrimaryKey = clusterPrimaryKey;
  query.expectedObjectClass = [GTLRatingAPIResponse class];
  return query;
}

+ (id)queryForHasUserAlreadyVotedWithClusterPrimaryKey:(NSString *)clusterPrimaryKey {
  NSString *methodName = @"ratingAPI.hasUserAlreadyVoted";
  GTLQueryRatingAPI *query = [self queryWithMethodName:methodName];
  query.clusterPrimaryKey = clusterPrimaryKey;
  query.expectedObjectClass = [GTLRatingAPIResponse class];
  return query;
}

@end
