/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLRatingAPI.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   ratingAPI/v1
// Description:
//   This API serves everything needed for Ratings

#import "GTLRatingAPIConstants.h"

#import "GTLRatingAPIJsonMap.h"
#import "GTLRatingAPIKeyResult.h"
#import "GTLRatingAPIResponse.h"

#import "GTLQueryRatingAPI.h"
#import "GTLServiceRatingAPI.h"
