/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLRatingAPIResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   ratingAPI/v1
// Description:
//   This API serves everything needed for Ratings
// Classes:
//   GTLRatingAPIResponse (0 custom class methods, 3 custom properties)

#import "GTLRatingAPIResponse.h"

#import "GTLRatingAPIJsonMap.h"

// ----------------------------------------------------------------------------
//
//   GTLRatingAPIResponse
//

@implementation GTLRatingAPIResponse
@dynamic entity, metadata, status;
@end
