/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLRatingAPIKeyResult.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   ratingAPI/v1
// Description:
//   This API serves everything needed for Ratings
// Classes:
//   GTLRatingAPIKeyResult (0 custom class methods, 1 custom properties)

#import "GTLRatingAPIKeyResult.h"

#import "GTLRatingAPIJsonMap.h"

// ----------------------------------------------------------------------------
//
//   GTLRatingAPIKeyResult
//

@implementation GTLRatingAPIKeyResult
@dynamic keys;
@end
