/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLRatingAPIResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   ratingAPI/v1
// Description:
//   This API serves everything needed for Ratings
// Classes:
//   GTLRatingAPIResponse (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLRatingAPIJsonMap;

// ----------------------------------------------------------------------------
//
//   GTLRatingAPIResponse
//

@interface GTLRatingAPIResponse : GTLObject
@property (retain) id entity;
@property (retain) GTLRatingAPIJsonMap *metadata;
@property (retain) NSNumber *status;  // intValue
@end
