/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLRatingAPIKeyResult.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   ratingAPI/v1
// Description:
//   This API serves everything needed for Ratings
// Classes:
//   GTLRatingAPIKeyResult (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLRatingAPIJsonMap;

// ----------------------------------------------------------------------------
//
//   GTLRatingAPIKeyResult
//

@interface GTLRatingAPIKeyResult : GTLObject
@property (retain) GTLRatingAPIJsonMap *keys;
@end
