/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLRatingAPIConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   ratingAPI/v1
// Description:
//   This API serves everything needed for Ratings

#import "GTLRatingAPIConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeRatingAPIUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
