/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLRatingAPIJsonMap.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   ratingAPI/v1
// Description:
//   This API serves everything needed for Ratings
// Classes:
//   GTLRatingAPIJsonMap (0 custom class methods, 0 custom properties)

#import "GTLRatingAPIJsonMap.h"

// ----------------------------------------------------------------------------
//
//   GTLRatingAPIJsonMap
//

@implementation GTLRatingAPIJsonMap
@end
