/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLRatingAPIJsonMap.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   ratingAPI/v1
// Description:
//   This API serves everything needed for Ratings
// Classes:
//   GTLRatingAPIJsonMap (0 custom class methods, 0 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLRatingAPIJsonMap
//

@interface GTLRatingAPIJsonMap : GTLObject
@end
