/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPISpot.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLSpotAPISpot (0 custom class methods, 16 custom properties)

#import "GTLSpotAPISpot.h"

#import "GTLSpotAPICluster.h"
#import "GTLSpotAPIKey.h"

// ----------------------------------------------------------------------------
//
//   GTLSpotAPISpot
//

@implementation GTLSpotAPISpot
@dynamic cluster, clusterRadiusInKm, clusterRadiusInMeter, dataStoreKey,
         descriptionProperty, latitude, longitude, maxClusterViews,
         maxNumberOfPOIsPerCluster, maxNumberOfViewsPerCluster, name,
         overallMaxPOINumberPerCluster, overallMaxViewNumberPerCluster,
         spotRadiusInKm, spotRadiusInMeter, topThreePictures;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"description"
                                forKey:@"descriptionProperty"];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [GTLSpotAPICluster class], @"cluster",
      [NSString class], @"topThreePictures",
      nil];
  return map;
}

@end
