/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPIClusterCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLSpotAPIClusterCollection (0 custom class methods, 1 custom properties)

#import "GTLSpotAPIClusterCollection.h"

#import "GTLSpotAPICluster.h"

// ----------------------------------------------------------------------------
//
//   GTLSpotAPIClusterCollection
//

@implementation GTLSpotAPIClusterCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLSpotAPICluster class]
                                forKey:@"items"];
  return map;
}

@end
