/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPISpot.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLSpotAPISpot (0 custom class methods, 16 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLSpotAPICluster;
@class GTLSpotAPIKey;

// ----------------------------------------------------------------------------
//
//   GTLSpotAPISpot
//

@interface GTLSpotAPISpot : GTLObject
@property (retain) NSArray *cluster;  // of GTLSpotAPICluster
@property (retain) NSNumber *clusterRadiusInKm;  // doubleValue
@property (retain) NSNumber *clusterRadiusInMeter;  // doubleValue
@property (retain) GTLSpotAPIKey *dataStoreKey;

// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (copy) NSString *descriptionProperty;

@property (retain) NSNumber *latitude;  // doubleValue
@property (retain) NSNumber *longitude;  // doubleValue
@property (retain) NSNumber *maxClusterViews;  // intValue
@property (retain) NSNumber *maxNumberOfPOIsPerCluster;  // intValue
@property (retain) NSNumber *maxNumberOfViewsPerCluster;  // intValue
@property (copy) NSString *name;
@property (retain) NSNumber *overallMaxPOINumberPerCluster;  // intValue
@property (retain) NSNumber *overallMaxViewNumberPerCluster;  // intValue
@property (retain) NSNumber *spotRadiusInKm;  // doubleValue
@property (retain) NSNumber *spotRadiusInMeter;  // doubleValue
@property (retain) NSArray *topThreePictures;  // of NSString
@end
