/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPIJsonMap.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLSpotAPIJsonMap (0 custom class methods, 0 custom properties)

#import "GTLSpotAPIJsonMap.h"

// ----------------------------------------------------------------------------
//
//   GTLSpotAPIJsonMap
//

@implementation GTLSpotAPIJsonMap
@end
