/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPILatLng.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLSpotAPILatLng (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLSpotAPILatLng
//

@interface GTLSpotAPILatLng : GTLObject
@property (retain) NSNumber *latitude;  // doubleValue
@property (retain) NSNumber *latitudeInternal;  // longLongValue
@property (retain) NSNumber *longitude;  // doubleValue
@property (retain) NSNumber *longitudeInternal;  // longLongValue
@property (retain) NSNumber *polar;  // boolValue
@end
