/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPIResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLSpotAPIResponse (0 custom class methods, 3 custom properties)

#import "GTLSpotAPIResponse.h"

#import "GTLSpotAPIJsonMap.h"

// ----------------------------------------------------------------------------
//
//   GTLSpotAPIResponse
//

@implementation GTLSpotAPIResponse
@dynamic entity, metadata, status;
@end
