/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPILatLng.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLSpotAPILatLng (0 custom class methods, 5 custom properties)

#import "GTLSpotAPILatLng.h"

// ----------------------------------------------------------------------------
//
//   GTLSpotAPILatLng
//

@implementation GTLSpotAPILatLng
@dynamic latitude, latitudeInternal, longitude, longitudeInternal, polar;
@end
