/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSpotAPIPointOfInterest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   spotAPI/v1
// Description:
//   API for Spots.
// Classes:
//   GTLSpotAPIPointOfInterest (0 custom class methods, 4 custom properties)

#import "GTLSpotAPIPointOfInterest.h"

#import "GTLSpotAPILatLng.h"

// ----------------------------------------------------------------------------
//
//   GTLSpotAPIPointOfInterest
//

@implementation GTLSpotAPIPointOfInterest
@dynamic countOfViews, location, pictureUrl, tags;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[NSString class]
                                forKey:@"tags"];
  return map;
}

@end
