/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-09 16:41:44 UTC)
 * on 2014-06-27 at 23:02:09 UTC 
 * Modify at your own risk.
 */

package com.appspot.flickeranalyser.spotAPI;

/**
 * Service definition for SpotAPI (v1).
 *
 * <p>
 * API for Spots.
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link SpotAPIRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class SpotAPI extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the spotAPI library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://flickeranalyser.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "spotAPI/v1/putSpotInCronQueue/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public SpotAPI(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  SpotAPI(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "evaluateCluster".
   *
   * This request holds the parameters needed by the the spotAPI server.  After setting any optional
   * parameters, call the {@link EvaluateCluster#execute()} method to invoke the remote operation.
   *
   * @param name
   * @param latitude
   * @param longitude
   * @param clusterRadius
   * @param description
   * @param spotRadius
   * @return the request
   */
  public EvaluateCluster evaluateCluster(java.lang.String name, java.lang.Double latitude, java.lang.Double longitude, java.lang.Double clusterRadius, java.lang.String description, java.lang.Double spotRadius) throws java.io.IOException {
    EvaluateCluster result = new EvaluateCluster(name, latitude, longitude, clusterRadius, description, spotRadius);
    initialize(result);
    return result;
  }

  public class EvaluateCluster extends SpotAPIRequest<com.appspot.flickeranalyser.spotAPI.model.Response> {

    private static final String REST_PATH = "{name}/{latitude}/{longitude}/{clusterRadius}/{description}/{spotRadius}";

    /**
     * Create a request for the method "evaluateCluster".
     *
     * This request holds the parameters needed by the the spotAPI server.  After setting any optional
     * parameters, call the {@link EvaluateCluster#execute()} method to invoke the remote operation.
     * <p> {@link EvaluateCluster#initialize(com.google.api.client.googleapis.services.AbstractGoogleC
     * lientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param name
     * @param latitude
     * @param longitude
     * @param clusterRadius
     * @param description
     * @param spotRadius
     * @since 1.13
     */
    protected EvaluateCluster(java.lang.String name, java.lang.Double latitude, java.lang.Double longitude, java.lang.Double clusterRadius, java.lang.String description, java.lang.Double spotRadius) {
      super(SpotAPI.this, "POST", REST_PATH, null, com.appspot.flickeranalyser.spotAPI.model.Response.class);
      this.name = com.google.api.client.util.Preconditions.checkNotNull(name, "Required parameter name must be specified.");
      this.latitude = com.google.api.client.util.Preconditions.checkNotNull(latitude, "Required parameter latitude must be specified.");
      this.longitude = com.google.api.client.util.Preconditions.checkNotNull(longitude, "Required parameter longitude must be specified.");
      this.clusterRadius = com.google.api.client.util.Preconditions.checkNotNull(clusterRadius, "Required parameter clusterRadius must be specified.");
      this.description = com.google.api.client.util.Preconditions.checkNotNull(description, "Required parameter description must be specified.");
      this.spotRadius = com.google.api.client.util.Preconditions.checkNotNull(spotRadius, "Required parameter spotRadius must be specified.");
    }

    @Override
    public EvaluateCluster setAlt(java.lang.String alt) {
      return (EvaluateCluster) super.setAlt(alt);
    }

    @Override
    public EvaluateCluster setFields(java.lang.String fields) {
      return (EvaluateCluster) super.setFields(fields);
    }

    @Override
    public EvaluateCluster setKey(java.lang.String key) {
      return (EvaluateCluster) super.setKey(key);
    }

    @Override
    public EvaluateCluster setOauthToken(java.lang.String oauthToken) {
      return (EvaluateCluster) super.setOauthToken(oauthToken);
    }

    @Override
    public EvaluateCluster setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EvaluateCluster) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EvaluateCluster setQuotaUser(java.lang.String quotaUser) {
      return (EvaluateCluster) super.setQuotaUser(quotaUser);
    }

    @Override
    public EvaluateCluster setUserIp(java.lang.String userIp) {
      return (EvaluateCluster) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String name;

    /**

     */
    public java.lang.String getName() {
      return name;
    }

    public EvaluateCluster setName(java.lang.String name) {
      this.name = name;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double latitude;

    /**

     */
    public java.lang.Double getLatitude() {
      return latitude;
    }

    public EvaluateCluster setLatitude(java.lang.Double latitude) {
      this.latitude = latitude;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double longitude;

    /**

     */
    public java.lang.Double getLongitude() {
      return longitude;
    }

    public EvaluateCluster setLongitude(java.lang.Double longitude) {
      this.longitude = longitude;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double clusterRadius;

    /**

     */
    public java.lang.Double getClusterRadius() {
      return clusterRadius;
    }

    public EvaluateCluster setClusterRadius(java.lang.Double clusterRadius) {
      this.clusterRadius = clusterRadius;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String description;

    /**

     */
    public java.lang.String getDescription() {
      return description;
    }

    public EvaluateCluster setDescription(java.lang.String description) {
      this.description = description;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double spotRadius;

    /**

     */
    public java.lang.Double getSpotRadius() {
      return spotRadius;
    }

    public EvaluateCluster setSpotRadius(java.lang.Double spotRadius) {
      this.spotRadius = spotRadius;
      return this;
    }

    @Override
    public EvaluateCluster set(String parameterName, Object value) {
      return (EvaluateCluster) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link SpotAPI}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link SpotAPI}. */
    @Override
    public SpotAPI build() {
      return new SpotAPI(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link SpotAPIRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setSpotAPIRequestInitializer(
        SpotAPIRequestInitializer spotapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(spotapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
