/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-05 at 18:30:19 UTC 
 * Modify at your own risk.
 */

package com.appspot.flickeranalyser.spotAPI.model;

/**
 * Model definition for Spot.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the spotAPI. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Spot extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Cluster> cluster;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double clusterRadiusInKm;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double clusterRadiusInMeter;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key dataStoreKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double latitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double longitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxClusterViews;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxNumberOfPOIsPerCluster;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxNumberOfViewsPerCluster;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer overallMaxPOINumberPerCluster;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer overallMaxViewNumberPerCluster;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double spotRadiusInKm;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double spotRadiusInMeter;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> topThreePictures;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Cluster> getCluster() {
    return cluster;
  }

  /**
   * @param cluster cluster or {@code null} for none
   */
  public Spot setCluster(java.util.List<Cluster> cluster) {
    this.cluster = cluster;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getClusterRadiusInKm() {
    return clusterRadiusInKm;
  }

  /**
   * @param clusterRadiusInKm clusterRadiusInKm or {@code null} for none
   */
  public Spot setClusterRadiusInKm(java.lang.Double clusterRadiusInKm) {
    this.clusterRadiusInKm = clusterRadiusInKm;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getClusterRadiusInMeter() {
    return clusterRadiusInMeter;
  }

  /**
   * @param clusterRadiusInMeter clusterRadiusInMeter or {@code null} for none
   */
  public Spot setClusterRadiusInMeter(java.lang.Double clusterRadiusInMeter) {
    this.clusterRadiusInMeter = clusterRadiusInMeter;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getDataStoreKey() {
    return dataStoreKey;
  }

  /**
   * @param dataStoreKey dataStoreKey or {@code null} for none
   */
  public Spot setDataStoreKey(Key dataStoreKey) {
    this.dataStoreKey = dataStoreKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public Spot setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLatitude() {
    return latitude;
  }

  /**
   * @param latitude latitude or {@code null} for none
   */
  public Spot setLatitude(java.lang.Double latitude) {
    this.latitude = latitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLongitude() {
    return longitude;
  }

  /**
   * @param longitude longitude or {@code null} for none
   */
  public Spot setLongitude(java.lang.Double longitude) {
    this.longitude = longitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxClusterViews() {
    return maxClusterViews;
  }

  /**
   * @param maxClusterViews maxClusterViews or {@code null} for none
   */
  public Spot setMaxClusterViews(java.lang.Integer maxClusterViews) {
    this.maxClusterViews = maxClusterViews;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxNumberOfPOIsPerCluster() {
    return maxNumberOfPOIsPerCluster;
  }

  /**
   * @param maxNumberOfPOIsPerCluster maxNumberOfPOIsPerCluster or {@code null} for none
   */
  public Spot setMaxNumberOfPOIsPerCluster(java.lang.Integer maxNumberOfPOIsPerCluster) {
    this.maxNumberOfPOIsPerCluster = maxNumberOfPOIsPerCluster;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxNumberOfViewsPerCluster() {
    return maxNumberOfViewsPerCluster;
  }

  /**
   * @param maxNumberOfViewsPerCluster maxNumberOfViewsPerCluster or {@code null} for none
   */
  public Spot setMaxNumberOfViewsPerCluster(java.lang.Integer maxNumberOfViewsPerCluster) {
    this.maxNumberOfViewsPerCluster = maxNumberOfViewsPerCluster;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Spot setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getOverallMaxPOINumberPerCluster() {
    return overallMaxPOINumberPerCluster;
  }

  /**
   * @param overallMaxPOINumberPerCluster overallMaxPOINumberPerCluster or {@code null} for none
   */
  public Spot setOverallMaxPOINumberPerCluster(java.lang.Integer overallMaxPOINumberPerCluster) {
    this.overallMaxPOINumberPerCluster = overallMaxPOINumberPerCluster;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getOverallMaxViewNumberPerCluster() {
    return overallMaxViewNumberPerCluster;
  }

  /**
   * @param overallMaxViewNumberPerCluster overallMaxViewNumberPerCluster or {@code null} for none
   */
  public Spot setOverallMaxViewNumberPerCluster(java.lang.Integer overallMaxViewNumberPerCluster) {
    this.overallMaxViewNumberPerCluster = overallMaxViewNumberPerCluster;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getSpotRadiusInKm() {
    return spotRadiusInKm;
  }

  /**
   * @param spotRadiusInKm spotRadiusInKm or {@code null} for none
   */
  public Spot setSpotRadiusInKm(java.lang.Double spotRadiusInKm) {
    this.spotRadiusInKm = spotRadiusInKm;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getSpotRadiusInMeter() {
    return spotRadiusInMeter;
  }

  /**
   * @param spotRadiusInMeter spotRadiusInMeter or {@code null} for none
   */
  public Spot setSpotRadiusInMeter(java.lang.Double spotRadiusInMeter) {
    this.spotRadiusInMeter = spotRadiusInMeter;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getTopThreePictures() {
    return topThreePictures;
  }

  /**
   * @param topThreePictures topThreePictures or {@code null} for none
   */
  public Spot setTopThreePictures(java.util.List<java.lang.String> topThreePictures) {
    this.topThreePictures = topThreePictures;
    return this;
  }

  @Override
  public Spot set(String fieldName, Object value) {
    return (Spot) super.set(fieldName, value);
  }

  @Override
  public Spot clone() {
    return (Spot) super.clone();
  }

}
